### ISSUE TITLE
The meaning of all relation symbols

### ISSUE THREAD

**Issue by chansey97** [eclipse/xsemantics#100]
Hi, I am a newbie to xsemantics.

I want to use xsemantics to implement my DLS's type system, but xsemantics use some conventional releation symbols in formal type systems.
I know a little about it (eg: <: is subtyping), but I can not understand all of it.
Is there any document explains the meaning of all these releation symbols?

RelationSymbol:
	'<!' | '!>' | '<<!' | '!>>' | '<~!' | '!~>' |
	':' | '<:' | ':>' | '<<' | '>>' | '~~' |
	'<|' | '|>' | '<-' | '-->' | '<~' | '~>' |
	'\\/' | '/\\'
;

Very thanks.

**Comment by LorenzoBettini** [comment]
you might want to follow the conventions: |-, |= and so on are for deductions (e.g., actual type system rules), <|, |> are for other subtyping relations, ->, are for reduction rules. There's no explanation in the documentation because they're related to type system and semantics conventions.

Please let me know if I can provide further help

**Comment by Guite** [comment]
> type system and semantics conventions

Maybe you can reference an external, general documentation about these? For beginners this is hard to understand if they are not familiar with those topics.

**Comment by LorenzoBettini** [comment]
there are too many references I'm afraid ;)

**Comment by chansey97** [comment]
Hi @LorenzoBettini,
I know that using xsemantics requires some knowledge of formal system types and I'd love to systematically learn these theories.
But before learn it, I hope to use xsemantics first, since it more concrete.

xsemantics uses many relational symbols, but they are just symbols, no name, so I can not search them on google.

For example：
I can search 'type system subtyping' in google and it return webpage https://en.wikipedia.org/wiki/Subtyping, in this webpage I can find symbol '<:'.
But if I search 'type system <:' on google, the return information is useless...

Can you tell me the English names of these relation symbols, like "<:" is "subtyping", so I can search reference on google by myself. (eg: type system 'keyword')
Best regards

**Comment by LorenzoBettini** [comment]
Have a look at this paper http://lucacardelli.name/Papers/TypeSystems.pdf

**Comment by LorenzoBettini** [comment]
I'm closing this issue now, since I provided a few references.
Please feel free to reopen it.
