### ISSUE TITLE
XSemantics Version for XText 2.13

### ISSUE THREAD

**Issue by ChristianHartmann** [eclipse/xsemantics#104]
The current version of XSemantics 1.12.1 is only compatible with XText 2.12, and not with the current XText version 2.13.

A compatible XSemantics version for XText 2.13 would be great.

**Comment by LorenzoBettini** [comment]
Actually, the sources in the git repo have already been ported to Xtext 2.13, see https://github.com/eclipse/xsemantics/pull/103, and a nightly version is available here https://ci.eclipse.org/xsemantics/job/xsemantics-nightly/lastSuccessfulBuild/artifact/releng/org.eclipse.xsemantics.repository/target/repository/

However, there's no official release yet.  Please keep in mind that now Xsemantics is an Eclipse projects, thus all the bundles have been renamed accordingly (it.xsemantics... -> org.eclipse.xsemantics...).

You may want to try the nightly version, just to update your dependencies with the new names... You will also have to manually remove the previous version and then install the new one.

I'm leaving this issue open till the official release

**Comment by LorenzoBettini** [comment]
I've updated the main README file with information about the milestones update site and Maven snapshots  (version 2.13.0 of Xsemantics is based on Xtext 2.13.0).

Please remember that bundle and Java packages have changed: 
it.xsemantics... -> org.eclipse.xsemantics...
