### ISSUE TITLE
No idea how to get it work with Xtext 2.14

### ISSUE THREAD

**Issue by czarly** [eclipse/xsemantics#109]
I tried a lot of things eventually messing up my xText project to the point of no return. But I couldn't get xSemantics going with the default Gradle setup of the current xText wizard.

**Comment by cdietrich** [comment]
did you make sure you dont get accidentially newer eclipse platform/jdt and EMF depenendencies pulled?

**Comment by cdietrich** [comment]
@LorenzoBettini besides that it looks like recent versions were not published to maven central

**Comment by LorenzoBettini** [comment]
@cdietrich they are, but as snapshots, since, as an Eclipse project, we still haven't performed any release, only milestones: we'll perform releases soon, since it has only recently approved.

**Comment by czarly** [comment]
thank you for reaching back. my ticket was intentionally unspecific since i got lost on my way and mainly wanted to point out that the documentation didn't get me started. for instance it was not clear to me how to add the it.xsemantics.runtime dependency in my eclipse project. after searching around in the settings to no avail, i found a quick fix suggestion in a generated source file to add exactly this dependency to my project which I accepted. That made the suggestion disappear but the import still couldn't be resolved. I figured the plugin version i installed has different package names now as it turned into a project under the eclipse umbrella. I ended up editing pom files and adding snapshot repositories,... as the project structure of a xtext project is complex enough and with most of the child projects i don't mess as i have no clue what they are doing, you get very quick to the point where you add missing dependencies to about every pom you find and clean / rebuild the workspace to flush caches that might or might not be involved. It's crucial to have a initial working configuration quickly to have a base to return to when things go wrong while learning and poking around.

**Comment by LorenzoBettini** [comment]
I'm afraid you hit this project during the transitioning phase, including the change of package names...
the documentation should be updated with that respect, isn't it?

In general, if you want to switch to Xsemantics, you should be already familiar with Xtext DSL development (including building systems... by the way, I'd suggest you to use Maven if you're starting with a new project... if you're already using gradle then I'm afraid I can't help)

**Comment by czarly** [comment]
I used this as [documentation](http://xsemantics.sourceforge.net/xsemantics-documentation/02-GettingStarted.html#Install) but i'm not sure if there is a more current version. Gradle was just the **Xtext** default when setting up the Eclipse project. As I said, I didn't make a conscious decision there. Before I used Maven a lot and Xtext a bit. I have to catch up with the Java world again after 6 years of NodeJS and SPAs.

**Comment by LorenzoBettini** [comment]
I'm afraid that link is old :(

**Comment by czarly** [comment]
Lets add the current one to the Github repositories README file :)

**Comment by czarly** [comment]
for the record: I found it! 

https://www.eclipse.org/Xtext/documentation/index.html

**Comment by lbordowitz** [comment]
I'm doing a little bit of work on the documentation in my spare time. See the wiki for progress on converting the xdoc to markdown. I'm also making some grammar edits for readability.

**Comment by LorenzoBettini** [comment]
The Xdoc format was useful because the Eclipse Help was generated from that... if you convert the documentation to Markdown, then you should also provide an automated mechanism to generate the corresponding Eclipse Help (during the Maven/Tycho build)...

**Comment by LorenzoBettini** [comment]
I'm closing this since I think it's stale by now, please feel free to re-open it if you still have problems
