### ISSUE TITLE
Caching support in Xsemantics

### ISSUE THREAD

**Issue by szschaler** [eclipse/xsemantics#121]
I am building a DSL with fairly complex derived state, which is needed when scoping, code completing, etc. As this is beginning to become noticeable in the responsiveness of the editor, I am looking at better support for caching. During my explorations, I noticed that you have had [similar issues in the past](https://www.eclipse.org/forums/index.php/mv/msg/639125/1233703/) and was wondering whether your problems were ever resolved (the forum entry cited isn't clear about this).

My current problem is described in https://www.eclipse.org/forums/index.php/t/1100186/. I had a quick look around the caching in Xsemantics and from this, it looks like you are using `OnChangeEvictingCache` pretty much directly.

I assume this means my problem would not be solved by switching to Xsemantics (or reusing some of your caching infrastructure), but wanted to check that I understand the situation correctly.

Many thanks,

Steffen

**Comment by LorenzoBettini** [comment]
Hi Steffen

I'm using the default cache implementation provided by Xtext. In my case, that's not a problem ;)

As suggested in the forum, if that does not fit your use case I guess you have to implement your own cache.

**Comment by szschaler** [comment]
Thanks for confirming. Cool project by the way.
