### ISSUE TITLE
Build an enviroment form a list

### ISSUE THREAD

**Issue by Johanvdberg** [eclipse/xsemantics#133]
Hallo

I want to build an environment from a list of variable previous defined. The syntax allow the use of  `empty, "var1" <- Type 1, "var2" << Type1  `  

How can  ` list = [["var1", Type1], .....] `  be added to the environment `G`?

**Comment by LorenzoBettini** [comment]
There's no explicit syntax for that, but you can use the Java API of the class representing the environment. You'll have to build such an environment before calling the rule. You can use the content assist for that.
