### ISSUE TITLE
[Question] Applying code generation to type derivation

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xsemantics#148]
In my current language, I find it necessary to define the semantics based on typing derivations rather than on expressions. I was wondering whether XSemantics has support for this, or what the best way would be to tackle this.

I currently have a complete formal specification of an expression language that I would like to implement. I already have implemented the type system, and my next step was to implement the semantics using code generation to Java.

As an example, consider the following formal semantical rule I have for arithmetic addition,

![E-Add](https://user-images.githubusercontent.com/47859223/141460394-946f0b35-25f1-42bf-a9a2-9a0b8edcb907.PNG)

which maps the typing derivation "if typing derivation `D1` concludes that `e1` has type `T` and typing derivation `D2` concludes that `e2` has type `T`, then `e1 + e2` has type `T`" to some expression that depends on the type `T` (i.e., the `+` operator is overloaded). Note: in more complex scenario's, I might need to inspect which typing rule was invoked to conclude that a subexpression `e1` has type `T`.

Now, if I want to implement this rule using a code generator, what would be a good approach to make the generator dependent on the typing derivation? E.g., I would like to write something like "if subexpression `e1` was derived using this rule, then generate this code, otherwise generate other code". Is there support for this? I couldn't find it in the documentation.

**Comment by LorenzoBettini** [comment]
Hi, in general, from a rule you can call any other rule even belonging to any other judgment. Thus, in the end, it's up to you to define rules and judgments appropriately and implement them, just as you said.
