### ISSUE TITLE
Xsemantics doesn't have a release build

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xsemantics#172]
At REGnosys, we are currently making extensive use of Xsemantics for the type system of the [Rosetta DSL](https://github.com/REGnosys/rosetta-dsl). However, our project will migrate this year to the Open Source Foundation FINOS, which doesn't allow releasing projects that depend on snapshots. Unfortunately, Xsemantics is currently only available as snapshot, so we were wondering: would it be possible to publish a release build?

**Comment by LorenzoBettini** [comment]
Thanks for mentioning that. I guess it's really time to make a release :) but are you referring to Maven artifacts that are in snapshot form only?

**Comment by SimonCockx** [comment]
I'm not sure what you mean. We have currently added the snapshot repo of sonatype to fetch `xsemantics`, i.e.,
```
<repository>
  <id>sonatype_snapshots</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```
Ideally, we would like to remove this repo and only depend on the release site, i.e.,
```
<repository>
  <id>sonatype_releases</id>
  <url>https://oss.sonatype.org/content/repositories/releases/</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
</repository>
```
If that makes sense.

**Comment by LorenzoBettini** [comment]
OK, so you're not worried about the p2 update site, but about the Maven snapshots. I think I can release Maven artifacts without snapshots.

**Comment by SimonCockx** [comment]
Hi @LorenzoBettini. By chance any update on this? We would love to see this released. In fact, if we can help with the release, we can definitely spend some time on this. We would be glad to help in any way!

**Comment by LorenzoBettini** [comment]
@SimonCockx, everything should be fixed now: disable the snapshot repositories and remove the -SNAPSHOT from the 1.22.0 xsemantics version :)

I'm closing this, but if anything goes wrong, please re-open this.

**Comment by minesh-s-patel** [comment]
Thanks @LorenzoBettini!

**Comment by hugohills-regnosys** [comment]
Great news, thanks!
